# ---- 内存控制 ----
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=2048m -XX:SoftRefLRUPolicyMSPerMB=50 -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m
kotlin.daemon.useFallbackStrategy=false
org.gradle.workers.max=4
kotlin.native.ignoreDisabledTargets=true

# ---- 编译速度 ----
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ---- KMP ----
kotlin.mpp.androidSourceSetLayoutVersion=2